### ISSUE TITLE
Running Prediction

### ISSUE THREAD

**Issue by aedirn** [jnkl314/DeepLabV3FineTuning#1]
Hi jnkl314 and any other users, 

This repo looks pretty interesting and useful. I cloned the repo and got the training to run, and now I am trying to use the fine-tuned model to make mask predictions on images. Only using the sample skydiving data for now, to make things easy. 

The code in main_inference seems the most relevant. It appears that the code opens png files from a temp directory (?) from how jnkl314 was running the code in Pycharm: 
`image = Image.open(f"/tmp/pycharm_project_782/03.03.20_saut_4/{idx:06}.png")` from line 29

Obviously we do not all have /tmp/pycharm_project_782/03.03.20_saut_4/ on our machines, so I set up my code to iterate through all files of sample_dataset/val/images (or any folder containing pngs). 

The part of jnkl314's code that is causing a problem is main_inference.py lines 29-39: 
    
    image = Image.open(f"/tmp/pycharm_project_782/03.03.20_saut_4/{idx:06}.png")
    image_np = np.asarray(image)
    # image_np = cv2.resize(image_np, 0.5, 0.5, cv2.INTER_CUBIC)
    width = int(image_np.shape[1] * 0.3)
    height = int(image_np.shape[0] * 0.3)
    dim = (width, height)
    image_np = cv2.resize(image_np, dim, interpolation=cv2.INTER_AREA)

    image = Image.fromarray(image_np)
    image = transforms_image(image)

When run, I get this error: 

Traceback (most recent call last):
  File "sources/main_mask_prediction.py", line 97, in <module>
    main()
[ this part of the trace just traces through the new functions I wrapped around jnkl314's code, unimportant ]
  File "sources/main_mask_prediction.py", line 59, in predict_one_image
    image = transforms_image(image)
  File "(...)\lib\site-packages\torchvision\transforms\transforms.py", line 61, in __call__
    img = t(img)
  File "(...)\lib\site-packages\torchvision\transforms\transforms.py", line 212, in __call__
    return F.normalize(tensor, self.mean, self.std, self.inplace)
  File "(...)\lib\site-packages\torchvision\transforms\functional.py", line 298, in normalize
    tensor.sub_(mean).div_(std)
RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 0

Calling transform on a freshly opened PNG, just how the code was uploaded, creates a size mismatch. Does this have to do with the image+label transform setup mentioned in the readme? If it does, why was this code uploaded without accounting for that? Or maybe the error is caused by an alpha channel in the PNG? 

Any help is greatly appreciated!

**Comment by aedirn** [comment]
It was the alpha channel in the image. Removing it solved the problem immediately.
